STOCKS_SHEET_ID = "1_Fj4lKv2esBxwwVn-ALfHNJp3OGNUChe8lQ5zfMkzD0"
PROPERTY_SHEET_ID = "142q0VXqiC6RWSjcS67BGR_ROVLYFtl61QgmRrYhoUkQ"
STOCKS_TAB = "Clean_Stocks"
PROPERTY_TAB = "Syndicate_Data"
DEFAULT_PERSONAL_TAX_RATE = 0.175
DEFAULT_COMPANY_TAX_RATE = 0.28
DEFAULT_BASELINE_DEBT_COST = 0.05
